package alphacraft.engine.resources;
/**
*  Describes the behaviour of a orbitalcommand in StarCraft II
*/
import java.util.ArrayList;
/**
* Describes the behaviour of an OrbitalCommand Center in java
*/
public class OrbitalCommand extends Building {

  private static final double energyRate = 0.5625;
  private static final double maxEnergy = 200.0;
  private static final int muleCost = 50;
  private static final int muleCode = -1;
  private static final int muleLifeSpan = 90;
  private static final GameElement[] depElements = {GameElement.COMMAND_CENTER, GameElement.BARRACKS};
  private static double currentEnergy = 0.0;
  private static int orbitalNo;
  private static ArrayList<Integer> mule;

  /**
  * Creates a new Orbtial Command.
  */
  public OrbitalCommand() {
    super(GameElement.COMMAND_CENTER, 150, 0, 35, 10, depElements);
  }

  /**
  * Adds a num command center.
  */
  public static void init(){
    orbitalNo++;
  }

  /**
  * Resets command centre to inital static.
  */
  public static void reset() {
    orbitalNo = 0;
    currentEnergy = 0;
    mule = new ArrayList<Integer>();
    currentEnergy = 0;
  }

  /**
  * Periodically disburbes to Gather Gas.
  *
  * @param currentTime the currentTime in the game
  */
  public static void disburseMULE(int currentTime) {
    //checks max enery has not been execeed
    if (muleCost <= currentEnergy) {
      mule.add(new Integer(currentTime + muleLifeSpan));
    }
    for (int i = 0; i < mule.size(); i++) {
      if (currentTime > mule.get(i).intValue()) {
        mule.remove(i);
      }
    }
    currentEnergy += orbitalNo * energyRate;
    if (currentEnergy > maxEnergy) {
      currentEnergy = maxEnergy;
    }
  }

  /**
  * Gets the total minerals generated by the mules.
  *
  * @return resourcs gathered
  */
  public static double MULELoad() {
    int noMules = mule.size();
    double load = 0;
    ArrayList<MineralPatch> mineralPatches = CommandCenter.getMineralPatches();
    while (noMules > 0 && MineralPatch.avaliablePatch() > 0){
      for (MineralPatch mineralPatch: mineralPatches) {
        if (!mineralPatch.depleted()) {
          load += mineralPatch.extract(muleCode);
          noMules--;
        }
      }
    }
    return load;
  }
}
